/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.PropertiesAndAgentsAndTasks;

import Modules.Noun;
import UI.PropertiesAndAgentsAndTasks.Agents.AgentsTree;
import UI.PropertiesAndAgentsAndTasks.PropertiesAndAgents;
import javax.swing.JPanel;

/**
 *
 * @author Emad Ali
 */
public class Agent extends javax.swing.JPanel {

    /**
     * Creates new form Agent
     */
    public Agent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        RadioButtonHemo = new javax.swing.JRadioButton();
        RadioButtonGroups = new javax.swing.JRadioButton();
        RadioButtonHetro = new javax.swing.JRadioButton();
        SaveAgentsButton = new javax.swing.JButton();

        setToolTipText("");

        jLabel1.setText("Number Of Agents:");

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        buttonGroup1.add(RadioButtonHemo);
        RadioButtonHemo.setText("All Agents are Hemogenious");
        RadioButtonHemo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonHemoActionPerformed(evt);
            }
        });

        buttonGroup1.add(RadioButtonGroups);
        RadioButtonGroups.setText("Groups of Hemogenious Agents");
        RadioButtonGroups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonGroupsActionPerformed(evt);
            }
        });

        buttonGroup1.add(RadioButtonHetro);
        RadioButtonHetro.setText("All Agents are Heterogeneous");
        RadioButtonHetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonHetroActionPerformed(evt);
            }
        });

        SaveAgentsButton.setText("Save");
        SaveAgentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveAgentsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RadioButtonHemo)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RadioButtonGroups)
                            .addComponent(RadioButtonHetro))
                        .addGap(18, 18, 18)
                        .addComponent(SaveAgentsButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(RadioButtonHemo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(SaveAgentsButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RadioButtonGroups)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RadioButtonHetro)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SaveAgentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveAgentsButtonActionPerformed
        /////////////// Getting input //////////////////////
        int numOfAgents;
        try {
            numOfAgents = Integer.parseInt(jTextField1.getText());
        } catch (NumberFormatException e) {
            System.out.println("XXX Number of Agents XXX");
            return;
        }
        int HemoLevel = -1;// -1:unknownYet, 0:AllHemo, 1:Groups, 2:AllHetero
        if (RadioButtonHemo.isSelected()) {
            HemoLevel = 0;
        } else if (RadioButtonGroups.isSelected()) {
            HemoLevel = 1;
        } else {
            if (RadioButtonHetro.isSelected()) {
                HemoLevel = 2;
            }
        }
        if (HemoLevel == -1) {
            System.out.println("XXX No choise for Hemo XXX");
            return;
        }
        /////////////// Updateing Num of Agents & Hemo //////////////////////
        if (Noun.getHemogeniousValue() == -1)// 1st time to click.
        {
            Modules.Agent.setHemogenious(HemoLevel);
            Modules.Agent.setNumberOfAgents(numOfAgents);
            Modules.Agent.setAgentsGroups(Modules.Agent.CreateListOfAgents(numOfAgents, HemoLevel));
        } else { // not the 1st time to click
            if (Modules.Agent.getNumberOfAgents() != numOfAgents) {// if number of agents changed
                if (Modules.Agent.getNumberOfAgents() > numOfAgents) {
                    System.out.println("WWW remove agents data may lose WWW");
                    //?return
                }
                Modules.Agent.changeNumberOfAgents(numOfAgents);
            }
            if (Noun.getHemogeniousValue() != HemoLevel) {//if hemo number of agents changed
                Noun.changeHemogenious(HemoLevel);
            }

        }
        SaveAgentsButton.setText("Saved");
        SaveAgentsButton.setEnabled(false);
        addHemogenetyPane(HemoLevel);
        AgentsTree.refreshTree();
    }//GEN-LAST:event_SaveAgentsButtonActionPerformed

    private void RadioButtonHemoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonHemoActionPerformed
        ChangeButtonNameSaveUpdate(0);
    }//GEN-LAST:event_RadioButtonHemoActionPerformed

    private void RadioButtonGroupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonGroupsActionPerformed
        ChangeButtonNameSaveUpdate(1);
    }//GEN-LAST:event_RadioButtonGroupsActionPerformed

    private void RadioButtonHetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonHetroActionPerformed
        ChangeButtonNameSaveUpdate(2);
    }//GEN-LAST:event_RadioButtonHetroActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        ChangeButtonNameSaveUpdate(Noun.getHemogeniousValue());
    }//GEN-LAST:event_jTextField1KeyReleased

    private void ChangeButtonNameSaveUpdate(int i) {
        if (Noun.getHemogeniousValue() == -1) {
            return;
        }
        try {
            if (Noun.getHemogeniousValue() != i || Integer.parseInt(jTextField1.getText()) != Modules.Agent.getNumberOfAgents()) {
                SaveAgentsButton.setText("Update");
                SaveAgentsButton.setEnabled(true);
            } else {
                SaveAgentsButton.setText("Saved");
                SaveAgentsButton.setEnabled(false);
            }
        } catch (NumberFormatException e) {
            return;
        }
    }

    private void addHemogenetyPane(int HemoLevel) {
        PropertiesAndAgents.jPanel3.removeAll();
        JPanel hemoPanel = null;
        switch (HemoLevel) { //0:AllHemo, 1:Groups, 2:AllHetero
            case 0:
                hemoPanel = new AgentsHemo();
                break;
            case 1:
                hemoPanel = new AgentsGroups();
                break;
            case 2:
                hemoPanel = new AgentsHetero();
                break;
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(PropertiesAndAgents.jPanel3);
        PropertiesAndAgents.jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(hemoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(hemoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
        );

        hemoPanel.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadioButtonGroups;
    private javax.swing.JRadioButton RadioButtonHemo;
    private javax.swing.JRadioButton RadioButtonHetro;
    private javax.swing.JButton SaveAgentsButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
