/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.PropertiesAndAgentsAndTasks;

import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author M Ghanem
 */
public class PropertiesTree extends javax.swing.JPanel {

    static DefaultMutableTreeNode PropTree = new javax.swing.tree.DefaultMutableTreeNode("Properties");

    /**
     * Creates new form AllProperties
     */
    public PropertiesTree() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();

        jTree1.setModel(new DefaultTreeModel(PropTree));
        jTree1.setMinimumSize(new java.awt.Dimension(100, 100));
        jTree1.setPreferredSize(new java.awt.Dimension(100, 100));
        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTree1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseClicked
        //System.out.println(evt);
    }//GEN-LAST:event_jTree1MouseClicked

    protected static void refreshTree() {
        PropertiesTree.PropTree = new javax.swing.tree.DefaultMutableTreeNode("Properties");
        for (Modules.Property p : Modules.Property.getProperties()) {
            DefaultMutableTreeNode node1 = new DefaultMutableTreeNode(p.getName() + " :: " + ((p.getType() == 0) ? "Boolean" : (p.getType() == 1) ? "Number" : "Text"));
            DefaultMutableTreeNode node2 = new DefaultMutableTreeNode(p.getValue() + ((p.getType() == 0 || "".equals(p.getMeteric())) ? "" : (" (" + p.getMeteric() + ")")));
            node1.add(node2);
            PropertiesTree.PropTree.add(node1);
            PropertiesTree.jTree1.setModel(new DefaultTreeModel(PropTree));
        }
        Property.resetPropertyUI();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    protected static javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
