/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.PropertiesAndAgentsAndTasks.Agents;

import java.util.ArrayList;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author M Ghanem
 */
public class AgentsTree extends javax.swing.JPanel {
    
    static DefaultMutableTreeNode AgentTree = new javax.swing.tree.DefaultMutableTreeNode("Agents");
    
    /**
     * Creates new form AllAgents
     */
    public AgentsTree() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();

        setAutoscrolls(true);

        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree1MouseClicked(evt);
            }
        });
        jTree1.setModel(new DefaultTreeModel(AgentTree));
        jTree1.setMinimumSize(new java.awt.Dimension(100, 0));
        jScrollPane1.setViewportView(jTree1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTree1MouseClicked(java.awt.event.MouseEvent evt) {                                    
        //System.out.println(evt);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    protected static javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables


    public static void refreshTree() {
        AgentsTree.AgentTree = new javax.swing.tree.DefaultMutableTreeNode("Agents");
        int i = 1;
        for (ArrayList<Modules.Agent> AllP : Modules.Agent.getAgentsGroups()) {
            DefaultMutableTreeNode node = new DefaultMutableTreeNode("Group (" + i++ + ")");
            DefaultMutableTreeNode node0;
            DefaultMutableTreeNode node1;
            DefaultMutableTreeNode node2;
            for (Modules.Agent a : AllP) {
                node0 = new DefaultMutableTreeNode("Agent" + a.getId());
                node1 = new DefaultMutableTreeNode("Name: " + a.getName());
                String prop = "Properties: ";
                boolean f = false;
                for (Modules.Property p : a.getProperties()) {
                    if (f) {
                        prop += ", ";
                    } else {
                        f = !f;
                    }
                    prop += p.getName() + "=" + p.getName() + "" + p.getMeteric();
                }
                node2 = new DefaultMutableTreeNode(prop);
                node0.add(node1);
                node0.add(node2);
                node.add(node0);
            }
            AgentsTree.AgentTree.add(node);
        }
        AgentsTree.jTree1.setModel(new DefaultTreeModel(AgentsTree.AgentTree));
    }
}
